apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: docker.io/busybox:1.36
          command: ["sh", "-c", "until nc -z mongodb 27017; do sleep 2; done"]
      containers:
        - name: mongo-api
          image: aharonsegal/mongo-container:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/
            - name: MONGO_DB
              value: testdb
            - name: MONGO_COLLECTION
              value: testcollection
            - name: JSON_FILE_PATH
              value: /app/app/employee_data_advanced.json